STATUS:Searching for applets
STATUS:Creating menu items
MSG   :Add menu Edit::New
MSG   :Add menu Structure::Window
MSG   :Add menu Structure::Control
MSG   :Add menu Electronic::DOS + bands
MSG   :Add menu Electronic::Local DOS+bands control
MSG   :Add menu Convergence::Forces
MSG   :Add menu Mechanics::Phonon dispersion
MSG   :Add menu Structure::Measure
MSG   :Add menu Convergence::Selected forces
MSG   :Add menu Structure::Show (old)
MSG   :Add menu Database::Commit
MSG   :Add menu Mechanics::Phonons k-points path
MSG   :Add menu Electronic::Local potential
MSG   :Add menu Edit::Multiply cell
MSG   :Add menu Electronic::Dielectric function
MSG   :Add menu Structure::Show/hide atoms
MSG   :Add menu Edit::Rotate atoms
MSG   :Add menu Edit::Edit sub-Z-matrix
MSG   :Add menu Structure::Lattice
MSG   :Add menu Mechanics::VAC
MSG   :Add menu Database::Query
MSG   :Add menu Edit::Move atoms
MSG   :Add menu Electronic::STM Control
MSG   :Add menu Structure::Export
MSG   :Add menu Convergence::Energy
MSG   :Add menu Edit::Builder
MSG   :Add menu Electronic::STM Window
MSG   :Add menu Edit::Info
MSG   :Add menu Electronic::View k-points
STATUS:Initializing toolbar buttons
STATUS:Initializing selection applet
STATUS:loading setup
ERROR : Can not read setup.xml
STATUS:setup loaded
STATUS:reading vasprun.xml
ERROR : Error reading property NAME
EXCEPT:Traceback (most recent call last):
          File "/usr/lib/python2.7/dist-packages/p4vasp/Property.py", line 159, in get
           self.value=self.read()
          File "/usr/lib/python2.7/dist-packages/p4vasp/Property.py", line 172, in read
           return apply(self.read_func,(self,))
          File "/usr/lib/python2.7/dist-packages/p4vasp/SystemPM.py", line 447, in <lambda>
           read=lambda x:x.manager.INCAR["SYSTEM"])
          File "/usr/lib/python2.7/dist-packages/p4vasp/Dictionary.py", line 314, in __getitem__
           raise KeyError(key)
        KeyError: 'SYSTEM'
       
STATUS:reading vasprun.xml OK
STATUS:OK
ERROR : Error reading property NAME
EXCEPT:Traceback (most recent call last):
          File "/usr/lib/python2.7/dist-packages/p4vasp/Property.py", line 159, in get
           self.value=self.read()
          File "/usr/lib/python2.7/dist-packages/p4vasp/Property.py", line 172, in read
           return apply(self.read_func,(self,))
          File "/usr/lib/python2.7/dist-packages/p4vasp/SystemPM.py", line 447, in <lambda>
           read=lambda x:x.manager.INCAR["SYSTEM"])
          File "/usr/lib/python2.7/dist-packages/p4vasp/Dictionary.py", line 314, in __getitem__
           raise KeyError(key)
        KeyError: 'SYSTEM'
       
STATUS:Parsing free energy sequence
STATUS:OK
ERROR : Smoothed PARCHG not available - press 'Smooth' to create.
ERROR : PARCHG not available in STM applet.
MSG   :read PARCHG from /home/adrian/Documentos/PARCHG
ERROR : Can not read /home/adrian/Documentos/PARCHG
ERROR : PARCHG not available in STM applet.
ERROR : PARCHG not available in STM applet.
ERROR : Smoothed PARCHG not available - press 'Smooth' to create.
ERROR : Smoothed PARCHG not available - press 'Smooth' to create.
ERROR : PARCHG not available in STM applet.
EXCEPT:Traceback (most recent call last):
          File "/usr/bin/p4v.py", line 660, in idle_func
           x=filter(lambda x,s=w.this:x.getWindowPtr()==s,applets())[0]
        IndexError: list index out of range
       
ERROR : Error reading property NAME
EXCEPT:Traceback (most recent call last):
          File "/usr/lib/python2.7/dist-packages/p4vasp/Property.py", line 159, in get
           self.value=self.read()
          File "/usr/lib/python2.7/dist-packages/p4vasp/Property.py", line 172, in read
           return apply(self.read_func,(self,))
          File "/usr/lib/python2.7/dist-packages/p4vasp/SystemPM.py", line 447, in <lambda>
           read=lambda x:x.manager.INCAR["SYSTEM"])
          File "/usr/lib/python2.7/dist-packages/p4vasp/Dictionary.py", line 314, in __getitem__
           raise KeyError(key)
        KeyError: 'SYSTEM'
       
EXCEPT:Traceback (most recent call last):
          File "/usr/bin/p4v.py", line 660, in idle_func
           x=filter(lambda x,s=w.this:x.getWindowPtr()==s,applets())[0]
        IndexError: list index out of range
       
EXCEPT:Traceback (most recent call last):
          File "/usr/bin/p4v.py", line 660, in idle_func
           x=filter(lambda x,s=w.this:x.getWindowPtr()==s,applets())[0]
        IndexError: list index out of range
       
EXCEPT:Traceback (most recent call last):
          File "/usr/bin/p4v.py", line 660, in idle_func
           x=filter(lambda x,s=w.this:x.getWindowPtr()==s,applets())[0]
        IndexError: list index out of range
       
EXCEPT:Traceback (most recent call last):
          File "/usr/bin/p4v.py", line 660, in idle_func
           x=filter(lambda x,s=w.this:x.getWindowPtr()==s,applets())[0]
        IndexError: list index out of range
       
